// Generated by gencpp from file styx_msgs/ChangeTargetSpeedResponse.msg
// DO NOT EDIT!


#ifndef STYX_MSGS_MESSAGE_CHANGETARGETSPEEDRESPONSE_H
#define STYX_MSGS_MESSAGE_CHANGETARGETSPEEDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace styx_msgs
{
template <class ContainerAllocator>
struct ChangeTargetSpeedResponse_
{
  typedef ChangeTargetSpeedResponse_<ContainerAllocator> Type;

  ChangeTargetSpeedResponse_()
    : feedback(false)  {
    }
  ChangeTargetSpeedResponse_(const ContainerAllocator& _alloc)
    : feedback(false)  {
  (void)_alloc;
    }



   typedef uint8_t _feedback_type;
  _feedback_type feedback;




  typedef boost::shared_ptr< ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeTargetSpeedResponse_

typedef ::styx_msgs::ChangeTargetSpeedResponse_<std::allocator<void> > ChangeTargetSpeedResponse;

typedef boost::shared_ptr< ::styx_msgs::ChangeTargetSpeedResponse > ChangeTargetSpeedResponsePtr;
typedef boost::shared_ptr< ::styx_msgs::ChangeTargetSpeedResponse const> ChangeTargetSpeedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace styx_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'styx_msgs': ['/home/student/Desktop/SelfDrivingCarND_SystemIntegration/ros/src/styx_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1f168a39479bedb24dba7a087426182";
  }

  static const char* value(const ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1f168a39479bedbULL;
  static const uint64_t static_value2 = 0x24dba7a087426182ULL;
};

template<class ContainerAllocator>
struct DataType< ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "styx_msgs/ChangeTargetSpeedResponse";
  }

  static const char* value(const ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool feedback\n\
";
  }

  static const char* value(const ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeTargetSpeedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::styx_msgs::ChangeTargetSpeedResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STYX_MSGS_MESSAGE_CHANGETARGETSPEEDRESPONSE_H
