(cl:defpackage styx_msgs-srv
  (:use )
  (:export
   "CHANGETARGETSPEED"
   "<CHANGETARGETSPEED-REQUEST>"
   "CHANGETARGETSPEED-REQUEST"
   "<CHANGETARGETSPEED-RESPONSE>"
   "CHANGETARGETSPEED-RESPONSE"
  ))

