// Generated by gencpp from file styx/ChangeControlPIDCoeff.msg
// DO NOT EDIT!


#ifndef STYX_MESSAGE_CHANGECONTROLPIDCOEFF_H
#define STYX_MESSAGE_CHANGECONTROLPIDCOEFF_H

#include <ros/service_traits.h>


#include <styx/ChangeControlPIDCoeffRequest.h>
#include <styx/ChangeControlPIDCoeffResponse.h>


namespace styx
{

struct ChangeControlPIDCoeff
{

typedef ChangeControlPIDCoeffRequest Request;
typedef ChangeControlPIDCoeffResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeControlPIDCoeff
} // namespace styx


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::styx::ChangeControlPIDCoeff > {
  static const char* value()
  {
    return "e613536b67df3009b4780803f4d01553";
  }

  static const char* value(const ::styx::ChangeControlPIDCoeff&) { return value(); }
};

template<>
struct DataType< ::styx::ChangeControlPIDCoeff > {
  static const char* value()
  {
    return "styx/ChangeControlPIDCoeff";
  }

  static const char* value(const ::styx::ChangeControlPIDCoeff&) { return value(); }
};


// service_traits::MD5Sum< ::styx::ChangeControlPIDCoeffRequest> should match 
// service_traits::MD5Sum< ::styx::ChangeControlPIDCoeff > 
template<>
struct MD5Sum< ::styx::ChangeControlPIDCoeffRequest>
{
  static const char* value()
  {
    return MD5Sum< ::styx::ChangeControlPIDCoeff >::value();
  }
  static const char* value(const ::styx::ChangeControlPIDCoeffRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::styx::ChangeControlPIDCoeffRequest> should match 
// service_traits::DataType< ::styx::ChangeControlPIDCoeff > 
template<>
struct DataType< ::styx::ChangeControlPIDCoeffRequest>
{
  static const char* value()
  {
    return DataType< ::styx::ChangeControlPIDCoeff >::value();
  }
  static const char* value(const ::styx::ChangeControlPIDCoeffRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::styx::ChangeControlPIDCoeffResponse> should match 
// service_traits::MD5Sum< ::styx::ChangeControlPIDCoeff > 
template<>
struct MD5Sum< ::styx::ChangeControlPIDCoeffResponse>
{
  static const char* value()
  {
    return MD5Sum< ::styx::ChangeControlPIDCoeff >::value();
  }
  static const char* value(const ::styx::ChangeControlPIDCoeffResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::styx::ChangeControlPIDCoeffResponse> should match 
// service_traits::DataType< ::styx::ChangeControlPIDCoeff > 
template<>
struct DataType< ::styx::ChangeControlPIDCoeffResponse>
{
  static const char* value()
  {
    return DataType< ::styx::ChangeControlPIDCoeff >::value();
  }
  static const char* value(const ::styx::ChangeControlPIDCoeffResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STYX_MESSAGE_CHANGECONTROLPIDCOEFF_H
