// Generated by gencpp from file styx/ChangeTargetSpeed.msg
// DO NOT EDIT!


#ifndef STYX_MESSAGE_CHANGETARGETSPEED_H
#define STYX_MESSAGE_CHANGETARGETSPEED_H

#include <ros/service_traits.h>


#include <styx/ChangeTargetSpeedRequest.h>
#include <styx/ChangeTargetSpeedResponse.h>


namespace styx
{

struct ChangeTargetSpeed
{

typedef ChangeTargetSpeedRequest Request;
typedef ChangeTargetSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeTargetSpeed
} // namespace styx


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::styx::ChangeTargetSpeed > {
  static const char* value()
  {
    return "fea0a386a47268810258a0f8d07589cc";
  }

  static const char* value(const ::styx::ChangeTargetSpeed&) { return value(); }
};

template<>
struct DataType< ::styx::ChangeTargetSpeed > {
  static const char* value()
  {
    return "styx/ChangeTargetSpeed";
  }

  static const char* value(const ::styx::ChangeTargetSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::styx::ChangeTargetSpeedRequest> should match 
// service_traits::MD5Sum< ::styx::ChangeTargetSpeed > 
template<>
struct MD5Sum< ::styx::ChangeTargetSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::styx::ChangeTargetSpeed >::value();
  }
  static const char* value(const ::styx::ChangeTargetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::styx::ChangeTargetSpeedRequest> should match 
// service_traits::DataType< ::styx::ChangeTargetSpeed > 
template<>
struct DataType< ::styx::ChangeTargetSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::styx::ChangeTargetSpeed >::value();
  }
  static const char* value(const ::styx::ChangeTargetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::styx::ChangeTargetSpeedResponse> should match 
// service_traits::MD5Sum< ::styx::ChangeTargetSpeed > 
template<>
struct MD5Sum< ::styx::ChangeTargetSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::styx::ChangeTargetSpeed >::value();
  }
  static const char* value(const ::styx::ChangeTargetSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::styx::ChangeTargetSpeedResponse> should match 
// service_traits::DataType< ::styx::ChangeTargetSpeed > 
template<>
struct DataType< ::styx::ChangeTargetSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::styx::ChangeTargetSpeed >::value();
  }
  static const char* value(const ::styx::ChangeTargetSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STYX_MESSAGE_CHANGETARGETSPEED_H
