(cl:defpackage styx-srv
  (:use )
  (:export
   "CHANGECONTROLPIDCOEFF"
   "<CHANGECONTROLPIDCOEFF-REQUEST>"
   "CHANGECONTROLPIDCOEFF-REQUEST"
   "<CHANGECONTROLPIDCOEFF-RESPONSE>"
   "CHANGECONTROLPIDCOEFF-RESPONSE"
   "CHANGETARGETSPEED"
   "<CHANGETARGETSPEED-REQUEST>"
   "CHANGETARGETSPEED-REQUEST"
   "<CHANGETARGETSPEED-RESPONSE>"
   "CHANGETARGETSPEED-RESPONSE"
  ))

